export const GET_USERINFO = 'GET_USERINOF' //获取用户详情
export const RECORD_ADDRESS = 'RECORD_ADDRESS';//保存经纬度
export const SAVE_GEOHASH = 'SAVE_GEOHASH';//保存gethash
export const RECORD_USERINFO = 'RECORD_USERINFO';//保存用户信息
export const SAVE_AVANDER = 'SAVE_AVANDER';//保存图片
export const  OUT_LOGIN = 'OUT_LOGIN';//退出登录
export const  RETSET_NAME = 'RETSET_NAME';//保存用户名
export const  SAVE_ADDRESS = 'SAVE_ADDRESS';//保存地址
export const ADD_ADDRESS = 'ADD_ADDRESS';//新增地址
export const SAVE_ADDDETAIL = 'SAVE_ADDDETAIL';//保存地址
export const CLEAR_CART = 'CLEAR_CART';
export const SAVE_ORDER = 'SAVE_ORDER';
